### ISSUE TITLE
HSR Program Meeting 2015-12-02

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#37]
Open issues:
- [x] Vote for the talks
- [x] Create the day program ( #25)
- [x] Discuss about catering (#33)
- [x] Take a look at the room
- [x] Check out the accessibility of the location (#26)
- [x] Talk about wifi
- [x] Talk about video recordings (#36)
- [x] Discuss t-shirts / lanyards

If there's anything else, I can add it to the list.

We'll document the progress in this issue.

**Comment by dbrgn** [comment]
For the record: we'll meet at 19:00 in room 6.112 (1st floor).

Please remember to read through the proposals before the meeting!

https://goo.gl/Sq8Fex

**Comment by dbrgn** [comment]
https://etherpad.coredump.ch/p/sps16-meeting-notes
